/* ================================================================
   languages.js — Language Registry & i18n Translations
   27 languages · NO Hebrew
   ================================================================ */

'use strict';

// ── Language Registry ─────────────────────────────────────────────────────────
const LANGUAGES = [
  { code:'en', nativeName:'English',          englishName:'English',    dir:'ltr' },
  { code:'ar', nativeName:'العربية',           englishName:'Arabic',     dir:'rtl' },
  { code:'fr', nativeName:'Français',          englishName:'French',     dir:'ltr' },
  { code:'de', nativeName:'Deutsch',           englishName:'German',     dir:'ltr' },
  { code:'es', nativeName:'Español',           englishName:'Spanish',    dir:'ltr' },
  { code:'pt', nativeName:'Português',         englishName:'Portuguese', dir:'ltr' },
  { code:'it', nativeName:'Italiano',          englishName:'Italian',    dir:'ltr' },
  { code:'ru', nativeName:'Русский',           englishName:'Russian',    dir:'ltr' },
  { code:'zh', nativeName:'中文',               englishName:'Chinese',    dir:'ltr' },
  { code:'ja', nativeName:'日本語',             englishName:'Japanese',   dir:'ltr' },
  { code:'ko', nativeName:'한국어',             englishName:'Korean',     dir:'ltr' },
  { code:'hi', nativeName:'हिन्दी',             englishName:'Hindi',      dir:'ltr' },
  { code:'tr', nativeName:'Türkçe',            englishName:'Turkish',    dir:'ltr' },
  { code:'nl', nativeName:'Nederlands',        englishName:'Dutch',      dir:'ltr' },
  { code:'pl', nativeName:'Polski',            englishName:'Polish',     dir:'ltr' },
  { code:'id', nativeName:'Bahasa Indonesia',  englishName:'Indonesian', dir:'ltr' },
  { code:'th', nativeName:'ไทย',               englishName:'Thai',       dir:'ltr' },
  { code:'vi', nativeName:'Tiếng Việt',        englishName:'Vietnamese', dir:'ltr' },
  { code:'fa', nativeName:'فارسی',             englishName:'Persian',    dir:'rtl' },
  { code:'ur', nativeName:'اردو',              englishName:'Urdu',       dir:'rtl' },
  { code:'bn', nativeName:'বাংলা',             englishName:'Bengali',    dir:'ltr' },
  { code:'el', nativeName:'Ελληνικά',          englishName:'Greek',      dir:'ltr' },
  { code:'cs', nativeName:'Čeština',           englishName:'Czech',      dir:'ltr' },
  { code:'sv', nativeName:'Svenska',           englishName:'Swedish',    dir:'ltr' },
  { code:'da', nativeName:'Dansk',             englishName:'Danish',     dir:'ltr' },
  { code:'no', nativeName:'Norsk',             englishName:'Norwegian',  dir:'ltr' },
  { code:'fi', nativeName:'Suomi',             englishName:'Finnish',    dir:'ltr' },
];

// ── Translations ──────────────────────────────────────────────────────────────
const TRANSLATIONS = {

  // ── English ──────────────────────────────────────────────────────────────────
  en: {
    brandName: 'MA3AK',
    brandSub:  'RAG System',
    aiLabel:   'AI Assistant',
    newChat:   'New Chat',
    send:      'Send',
    answer:    'Answer',
    evidence:  'Evidence',
    sources:   'Sources',
    confidence:'Confidence',
    page:      'Page',
    section:   'Section',
    placeholder:'Ask a clinical question...',
    inputHint: 'Enter to send · Shift+Enter for new line',
    loading:   'Generating answer...',
    insufficient:    'Insufficient Evidence',
    insufficientMsg: 'The available clinical documents do not contain enough information to safely answer this question.',
    confHigh:  'High',
    confMed:   'Medium',
    confLow:   'Low',
    confInsuf: 'Insufficient',
    errNetwork:'Network error. Please check your connection and try again.',
    errServer: 'The server encountered an error. Please try again.',
    errUnavail:'The RAG service is currently unavailable. Make sure the backend server is running.',
    wTitle:    'MA3AK',
    wSub:      'Ask questions based on the available clinical evidence.',
    ex0: '• What is the recommended blood pressure target?',
    ex1: '• What are the first-line treatment options for hypertension?',
    ex2: '• Which patients require additional cardiovascular monitoring?',
    searchLang:'Search languages...',
    noLang:    'No languages found',
  },

  // ── Arabic ────────────────────────────────────────────────────────────────────
  ar: {
    brandName: 'MA3AK',
    brandSub:  'RAG System',
    aiLabel:   'المساعد الذكي',
    newChat:   'محادثة جديدة',
    send:      'إرسال',
    answer:    'الإجابة',
    evidence:  'الأدلة',
    sources:   'المصادر',
    confidence:'درجة الثقة',
    page:      'الصفحة',
    section:   'القسم',
    placeholder:'اكتب سؤالك الطبي...',
    inputHint: 'Enter للإرسال · Shift+Enter لسطر جديد',
    loading:   'جاري إنشاء الإجابة...',
    insufficient:    'أدلة غير كافية',
    insufficientMsg: 'المستندات السريرية المتاحة لا تحتوي على معلومات كافية للإجابة على هذا السؤال بأمان.',
    confHigh:  'مرتفعة',
    confMed:   'متوسطة',
    confLow:   'منخفضة',
    confInsuf: 'غير كافية',
    errNetwork:'خطأ في الشبكة. يرجى التحقق من اتصالك والمحاولة مجدداً.',
    errServer: 'حدث خطأ في الخادم. يرجى المحاولة مجدداً.',
    errUnavail:'الخدمة غير متاحة حالياً. يرجى التأكد من تشغيل الخادم الخلفي.',
    wTitle:    'MA3AK',
    wSub:      'اطرح أسئلة مستندة إلى الأدلة السريرية المتاحة.',
    ex0: '• ما هو هدف ضغط الدم الموصى به؟',
    ex1: '• ما هي خيارات العلاج الأولى لارتفاع ضغط الدم؟',
    ex2: '• أي المرضى يحتاجون إلى مراقبة قلبية وعائية إضافية؟',
    searchLang:'ابحث عن لغة...',
    noLang:    'لا توجد لغات مطابقة',
  },

  // ── French ────────────────────────────────────────────────────────────────────
  fr: {
    brandName: 'MA3AK',
    brandSub:  'RAG System',
    aiLabel:   'Assistant IA',
    newChat:   'Nouvelle discussion',
    send:      'Envoyer',
    answer:    'Réponse',
    evidence:  'Preuves',
    sources:   'Sources',
    confidence:'Confiance',
    page:      'Page',
    section:   'Section',
    placeholder:'Posez une question clinique...',
    inputHint: 'Entrée pour envoyer · Shift+Entrée pour nouvelle ligne',
    loading:   'Génération de la réponse...',
    insufficient:    'Preuves insuffisantes',
    insufficientMsg: 'Les documents cliniques disponibles ne contiennent pas suffisamment d\'informations pour répondre à cette question en toute sécurité.',
    confHigh:  'Élevée',
    confMed:   'Moyenne',
    confLow:   'Faible',
    confInsuf: 'Insuffisante',
    errNetwork:'Erreur réseau. Vérifiez votre connexion et réessayez.',
    errServer: 'Le serveur a rencontré une erreur. Veuillez réessayer.',
    errUnavail:'Le service RAG est indisponible. Assurez-vous que le serveur est démarré.',
    wTitle:    'MA3AK',
    wSub:      'Posez des questions basées sur les preuves cliniques disponibles.',
    ex0: '• Quel est l\'objectif tensionnel recommandé ?',
    ex1: '• Quels sont les traitements de première intention pour l\'hypertension ?',
    ex2: '• Quels patients nécessitent une surveillance cardiovasculaire supplémentaire ?',
    searchLang:'Rechercher une langue...',
    noLang:    'Aucune langue trouvée',
  },

  // ── German ────────────────────────────────────────────────────────────────────
  de: {
    brandName: 'MA3AK',
    brandSub:  'RAG System',
    aiLabel:   'KI-Assistent',
    newChat:   'Neues Gespräch',
    send:      'Senden',
    answer:    'Antwort',
    evidence:  'Belege',
    sources:   'Quellen',
    confidence:'Konfidenz',
    page:      'Seite',
    section:   'Abschnitt',
    placeholder:'Klinische Frage stellen...',
    inputHint: 'Enter zum Senden · Shift+Enter für neue Zeile',
    loading:   'Antwort wird generiert...',
    insufficient:    'Unzureichende Belege',
    insufficientMsg: 'Die verfügbaren klinischen Dokumente enthalten nicht genügend Informationen, um diese Frage sicher zu beantworten.',
    confHigh:  'Hoch',
    confMed:   'Mittel',
    confLow:   'Niedrig',
    confInsuf: 'Unzureichend',
    errNetwork:'Netzwerkfehler. Bitte Verbindung prüfen und erneut versuchen.',
    errServer: 'Der Server hat einen Fehler festgestellt. Bitte erneut versuchen.',
    errUnavail:'Der RAG-Dienst ist nicht verfügbar. Bitte sicherstellen, dass das Backend läuft.',
    wTitle:    'MA3AK',
    wSub:      'Stellen Sie Fragen basierend auf klinischen Belegen.',
    ex0: '• Was ist der empfohlene Blutdruckzielwert?',
    ex1: '• Welche Erstlinientherapien gibt es bei Hypertonie?',
    ex2: '• Welche Patienten benötigen kardiovaskuläre Überwachung?',
    searchLang:'Sprache suchen...',
    noLang:    'Keine Sprachen gefunden',
  },

  // ── Spanish ───────────────────────────────────────────────────────────────────
  es: {
    brandName: 'MA3AK',
    brandSub:  'RAG System',
    aiLabel:   'Asistente IA',
    newChat:   'Nueva conversación',
    send:      'Enviar',
    answer:    'Respuesta',
    evidence:  'Evidencia',
    sources:   'Fuentes',
    confidence:'Confianza',
    page:      'Página',
    section:   'Sección',
    placeholder:'Haga una pregunta clínica...',
    inputHint: 'Enter para enviar · Shift+Enter para nueva línea',
    loading:   'Generando respuesta...',
    insufficient:    'Evidencia insuficiente',
    insufficientMsg: 'Los documentos clínicos disponibles no contienen suficiente información para responder a esta pregunta de forma segura.',
    confHigh:  'Alta',
    confMed:   'Media',
    confLow:   'Baja',
    confInsuf: 'Insuficiente',
    errNetwork:'Error de red. Verifique su conexión e inténtelo de nuevo.',
    errServer: 'El servidor encontró un error. Inténtelo de nuevo.',
    errUnavail:'El servicio RAG no está disponible. Asegúrese de que el backend esté ejecutándose.',
    wTitle:    'MA3AK',
    wSub:      'Haga preguntas basadas en la evidencia clínica disponible.',
    ex0: '• ¿Cuál es el objetivo de presión arterial recomendado?',
    ex1: '• ¿Cuáles son los tratamientos de primera línea para la hipertensión?',
    ex2: '• ¿Qué pacientes requieren monitoreo cardiovascular adicional?',
    searchLang:'Buscar idioma...',
    noLang:    'No se encontraron idiomas',
  },

  // ── Portuguese ────────────────────────────────────────────────────────────────
  pt: {
    brandName: 'MA3AK',
    brandSub:  'RAG System',
    aiLabel:   'Assistente IA',
    newChat:   'Nova conversa',
    send:      'Enviar',
    answer:    'Resposta',
    evidence:  'Evidência',
    sources:   'Fontes',
    confidence:'Confiança',
    page:      'Página',
    section:   'Seção',
    placeholder:'Faça uma pergunta clínica...',
    inputHint: 'Enter para enviar · Shift+Enter para nova linha',
    loading:   'Gerando resposta...',
    insufficient:    'Evidência insuficiente',
    insufficientMsg: 'Os documentos clínicos disponíveis não contêm informações suficientes para responder a esta pergunta com segurança.',
    confHigh:  'Alta',
    confMed:   'Média',
    confLow:   'Baixa',
    confInsuf: 'Insuficiente',
    errNetwork:'Erro de rede. Verifique sua conexão e tente novamente.',
    errServer: 'O servidor encontrou um erro. Tente novamente.',
    errUnavail:'O serviço RAG está indisponível. Certifique-se de que o backend está em execução.',
    wTitle:    'MA3AK',
    wSub:      'Faça perguntas baseadas nas evidências clínicas disponíveis.',
    ex0: '• Qual é o alvo de pressão arterial recomendado?',
    ex1: '• Quais são as opções de tratamento de primeira linha para hipertensão?',
    ex2: '• Quais pacientes requerem monitoramento cardiovascular adicional?',
    searchLang:'Pesquisar idioma...',
    noLang:    'Nenhum idioma encontrado',
  },

  // ── Italian ───────────────────────────────────────────────────────────────────
  it: {
    brandName: 'MA3AK',
    brandSub:  'RAG System',
    aiLabel:   'Assistente IA',
    newChat:   'Nuova chat',
    send:      'Invia',
    answer:    'Risposta',
    evidence:  'Evidenza',
    sources:   'Fonti',
    confidence:'Affidabilità',
    page:      'Pagina',
    section:   'Sezione',
    placeholder:'Poni una domanda clinica...',
    inputHint: 'Invio per inviare · Shift+Invio per nuova riga',
    loading:   'Generazione risposta...',
    insufficient:    'Evidenza insufficiente',
    insufficientMsg: 'I documenti clinici disponibili non contengono informazioni sufficienti per rispondere a questa domanda in modo sicuro.',
    confHigh:  'Alta',
    confMed:   'Media',
    confLow:   'Bassa',
    confInsuf: 'Insufficiente',
    errNetwork:'Errore di rete. Verifica la connessione e riprova.',
    errServer: 'Il server ha riscontrato un errore. Riprova.',
    errUnavail:'Il servizio RAG non è disponibile. Assicurati che il backend sia in esecuzione.',
    wTitle:    'MA3AK',
    wSub:      'Poni domande basate sulle evidenze cliniche disponibili.',
    ex0: '• Qual è l\'obiettivo di pressione arteriosa raccomandato?',
    ex1: '• Quali sono le opzioni di trattamento di prima linea per l\'ipertensione?',
    ex2: '• Quali pazienti richiedono un monitoraggio cardiovascolare aggiuntivo?',
    searchLang:'Cerca lingua...',
    noLang:    'Nessuna lingua trovata',
  },

  // ── Russian ───────────────────────────────────────────────────────────────────
  ru: {
    brandName: 'MA3AK',
    brandSub:  'RAG System',
    aiLabel:   'ИИ-Ассистент',
    newChat:   'Новый чат',
    send:      'Отправить',
    answer:    'Ответ',
    evidence:  'Доказательства',
    sources:   'Источники',
    confidence:'Уверенность',
    page:      'Стр.',
    section:   'Раздел',
    placeholder:'Задайте клинический вопрос...',
    inputHint: 'Enter для отправки · Shift+Enter для новой строки',
    loading:   'Генерация ответа...',
    insufficient:    'Недостаточно доказательств',
    insufficientMsg: 'Доступные клинические документы не содержат достаточно информации для безопасного ответа на этот вопрос.',
    confHigh:  'Высокая',
    confMed:   'Средняя',
    confLow:   'Низкая',
    confInsuf: 'Недостаточная',
    errNetwork:'Ошибка сети. Проверьте подключение и повторите попытку.',
    errServer: 'Произошла ошибка сервера. Повторите попытку.',
    errUnavail:'Служба RAG недоступна. Убедитесь, что бэкенд запущен.',
    wTitle:    'MA3AK',
    wSub:      'Задавайте вопросы на основе клинических данных.',
    ex0: '• Каков рекомендуемый целевой уровень артериального давления?',
    ex1: '• Каковы варианты лечения первой линии при гипертонии?',
    ex2: '• Каким пациентам требуется дополнительный кардиоваскулярный мониторинг?',
    searchLang:'Поиск языка...',
    noLang:    'Языки не найдены',
  },

  // ── Chinese ───────────────────────────────────────────────────────────────────
  zh: {
    brandName: 'MA3AK',
    brandSub:  'RAG System',
    aiLabel:   'AI助手',
    newChat:   '新对话',
    send:      '发送',
    answer:    '回答',
    evidence:  '证据',
    sources:   '来源',
    confidence:'可信度',
    page:      '页',
    section:   '章节',
    placeholder:'提出临床问题...',
    inputHint: 'Enter发送 · Shift+Enter换行',
    loading:   '正在生成答案...',
    insufficient:    '证据不足',
    insufficientMsg: '现有临床文件中没有足够的信息来安全回答此问题。',
    confHigh:  '高',
    confMed:   '中',
    confLow:   '低',
    confInsuf: '不足',
    errNetwork:'网络错误。请检查您的连接并重试。',
    errServer: '服务器遇到错误。请重试。',
    errUnavail:'RAG服务当前不可用。请确保后端正在运行。',
    wTitle:    'MA3AK',
    wSub:      '基于现有临床证据提问。',
    ex0: '• 推荐的血压目标是多少？',
    ex1: '• 高血压的一线治疗选择是什么？',
    ex2: '• 哪些患者需要额外的心血管监测？',
    searchLang:'搜索语言...',
    noLang:    '未找到语言',
  },

  // ── Japanese ──────────────────────────────────────────────────────────────────
  ja: {
    brandName: 'MA3AK',
    brandSub:  'RAG System',
    aiLabel:   'AIアシスタント',
    newChat:   '新しいチャット',
    send:      '送信',
    answer:    '回答',
    evidence:  'エビデンス',
    sources:   '出典',
    confidence:'信頼度',
    page:      'ページ',
    section:   'セクション',
    placeholder:'臨床的な質問をしてください...',
    inputHint: 'Enterで送信 · Shift+Enterで改行',
    loading:   '回答を生成しています...',
    insufficient:    'エビデンス不足',
    insufficientMsg: '利用可能な臨床文書には、この質問に安全に答えるのに十分な情報が含まれていません。',
    confHigh:  '高い',
    confMed:   '中程度',
    confLow:   '低い',
    confInsuf: '不十分',
    errNetwork:'ネットワークエラー。接続を確認して再試行してください。',
    errServer: 'サーバーでエラーが発生しました。再試行してください。',
    errUnavail:'RAGサービスは現在利用できません。バックエンドが実行されていることを確認してください。',
    wTitle:    'MA3AK',
    wSub:      '利用可能な臨床エビデンスに基づいて質問してください。',
    ex0: '• 推奨される血圧目標値は何ですか？',
    ex1: '• 高血圧の第一選択治療は何ですか？',
    ex2: '• どの患者に追加の心血管モニタリングが必要ですか？',
    searchLang:'言語を検索...',
    noLang:    '言語が見つかりません',
  },

  // ── Korean ────────────────────────────────────────────────────────────────────
  ko: {
    brandName: 'MA3AK',
    brandSub:  'RAG System',
    aiLabel:   'AI 보조자',
    newChat:   '새 채팅',
    send:      '전송',
    answer:    '답변',
    evidence:  '근거',
    sources:   '출처',
    confidence:'신뢰도',
    page:      '페이지',
    section:   '섹션',
    placeholder:'임상 질문을 입력하세요...',
    inputHint: 'Enter로 전송 · Shift+Enter로 새 줄',
    loading:   '답변 생성 중...',
    insufficient:    '근거 부족',
    insufficientMsg: '이용 가능한 임상 문서에는 이 질문에 안전하게 답변할 수 있는 충분한 정보가 없습니다.',
    confHigh:  '높음',
    confMed:   '보통',
    confLow:   '낮음',
    confInsuf: '불충분',
    errNetwork:'네트워크 오류. 연결을 확인하고 다시 시도하세요.',
    errServer: '서버에서 오류가 발생했습니다. 다시 시도하세요.',
    errUnavail:'RAG 서비스를 현재 사용할 수 없습니다. 백엔드가 실행 중인지 확인하세요.',
    wTitle:    'MA3AK',
    wSub:      '이용 가능한 임상 근거를 기반으로 질문하세요.',
    ex0: '• 권장 혈압 목표는 무엇입니까?',
    ex1: '• 고혈압의 1차 치료 옵션은 무엇입니까?',
    ex2: '• 어떤 환자에게 추가적인 심혈관 모니터링이 필요합니까?',
    searchLang:'언어 검색...',
    noLang:    '언어를 찾을 수 없습니다',
  },

  // ── Hindi ─────────────────────────────────────────────────────────────────────
  hi: {
    brandName: 'MA3AK',
    brandSub:  'RAG System',
    aiLabel:   'AI सहायक',
    newChat:   'नई बातचीत',
    send:      'भेजें',
    answer:    'उत्तर',
    evidence:  'प्रमाण',
    sources:   'स्रोत',
    confidence:'विश्वास',
    page:      'पृष्ठ',
    section:   'अनुभाग',
    placeholder:'नैदानिक प्रश्न पूछें...',
    inputHint: 'Enter भेजने के लिए · Shift+Enter नई पंक्ति',
    loading:   'उत्तर तैयार हो रहा है...',
    insufficient:    'अपर्याप्त प्रमाण',
    insufficientMsg: 'उपलब्ध नैदानिक दस्तावेज़ों में इस प्रश्न का सुरक्षित उत्तर देने के लिए पर्याप्त जानकारी नहीं है।',
    confHigh:  'उच्च',
    confMed:   'मध्यम',
    confLow:   'निम्न',
    confInsuf: 'अपर्याप्त',
    errNetwork:'नेटवर्क त्रुटि। कृपया अपना कनेक्शन जाँचें और पुनः प्रयास करें।',
    errServer: 'सर्वर में त्रुटि हुई। कृपया पुनः प्रयास करें।',
    errUnavail:'RAG सेवा अनुपलब्ध है। सुनिश्चित करें कि बैकएंड चल रहा है।',
    wTitle:    'MA3AK',
    wSub:      'उपलब्ध नैदानिक साक्ष्य के आधार पर प्रश्न पूछें।',
    ex0: '• अनुशंसित रक्तचाप लक्ष्य क्या है?',
    ex1: '• उच्च रक्तचाप के लिए प्रथम-पंक्ति उपचार विकल्प क्या हैं?',
    ex2: '• किन रोगियों को अतिरिक्त हृदय संबंधी निगरानी की आवश्यकता है?',
    searchLang:'भाषा खोजें...',
    noLang:    'कोई भाषा नहीं मिली',
  },

  // ── Turkish ───────────────────────────────────────────────────────────────────
  tr: {
    brandName: 'MA3AK',
    brandSub:  'RAG System',
    aiLabel:   'AI Asistanı',
    newChat:   'Yeni Sohbet',
    send:      'Gönder',
    answer:    'Yanıt',
    evidence:  'Kanıt',
    sources:   'Kaynaklar',
    confidence:'Güven',
    page:      'Sayfa',
    section:   'Bölüm',
    placeholder:'Klinik bir soru sorun...',
    inputHint: 'Enter\'a bas göndermek için · Shift+Enter yeni satır',
    loading:   'Yanıt oluşturuluyor...',
    insufficient:    'Yetersiz Kanıt',
    insufficientMsg: 'Mevcut klinik belgeler bu soruyu güvenli bir şekilde yanıtlamak için yeterli bilgi içermiyor.',
    confHigh:  'Yüksek',
    confMed:   'Orta',
    confLow:   'Düşük',
    confInsuf: 'Yetersiz',
    errNetwork:'Ağ hatası. Bağlantınızı kontrol edip tekrar deneyin.',
    errServer: 'Sunucu bir hatayla karşılaştı. Lütfen tekrar deneyin.',
    errUnavail:'RAG servisi şu anda kullanılamıyor. Backend\'in çalıştığından emin olun.',
    wTitle:    'MA3AK',
    wSub:      'Mevcut klinik kanıtlara dayalı sorular sorun.',
    ex0: '• Önerilen kan basıncı hedefi nedir?',
    ex1: '• Hipertansiyon için birinci basamak tedavi seçenekleri nelerdir?',
    ex2: '• Hangi hastalar ek kardiyovasküler izlem gerektirir?',
    searchLang:'Dil ara...',
    noLang:    'Dil bulunamadı',
  },

  // ── Dutch ─────────────────────────────────────────────────────────────────────
  nl: {
    brandName: 'MA3AK',
    brandSub:  'RAG System',
    aiLabel:   'AI-Assistent',
    newChat:   'Nieuw gesprek',
    send:      'Verzenden',
    answer:    'Antwoord',
    evidence:  'Bewijs',
    sources:   'Bronnen',
    confidence:'Betrouwbaarheid',
    page:      'Pagina',
    section:   'Sectie',
    placeholder:'Stel een klinische vraag...',
    inputHint: 'Enter om te verzenden · Shift+Enter voor nieuwe regel',
    loading:   'Antwoord genereren...',
    insufficient:    'Onvoldoende bewijs',
    insufficientMsg: 'De beschikbare klinische documenten bevatten niet genoeg informatie om deze vraag veilig te beantwoorden.',
    confHigh:  'Hoog',
    confMed:   'Gemiddeld',
    confLow:   'Laag',
    confInsuf: 'Onvoldoende',
    errNetwork:'Netwerkfout. Controleer uw verbinding en probeer opnieuw.',
    errServer: 'De server heeft een fout ondervonden. Probeer opnieuw.',
    errUnavail:'De RAG-dienst is momenteel niet beschikbaar. Zorg ervoor dat de backend actief is.',
    wTitle:    'MA3AK',
    wSub:      'Stel vragen op basis van het beschikbare klinische bewijs.',
    ex0: '• Wat is het aanbevolen bloeddrukdoel?',
    ex1: '• Wat zijn de eerstelijns behandelopties voor hypertensie?',
    ex2: '• Welke patiënten vereisen extra cardiovasculaire monitoring?',
    searchLang:'Taal zoeken...',
    noLang:    'Geen talen gevonden',
  },

  // ── Polish ────────────────────────────────────────────────────────────────────
  pl: {
    brandName: 'MA3AK',
    brandSub:  'RAG System',
    aiLabel:   'Asystent AI',
    newChat:   'Nowa rozmowa',
    send:      'Wyślij',
    answer:    'Odpowiedź',
    evidence:  'Dowody',
    sources:   'Źródła',
    confidence:'Pewność',
    page:      'Strona',
    section:   'Sekcja',
    placeholder:'Zadaj pytanie kliniczne...',
    inputHint: 'Enter, aby wysłać · Shift+Enter dla nowej linii',
    loading:   'Generowanie odpowiedzi...',
    insufficient:    'Niewystarczające dowody',
    insufficientMsg: 'Dostępne dokumenty kliniczne nie zawierają wystarczających informacji, aby bezpiecznie odpowiedzieć na to pytanie.',
    confHigh:  'Wysoka',
    confMed:   'Średnia',
    confLow:   'Niska',
    confInsuf: 'Niewystarczająca',
    errNetwork:'Błąd sieci. Sprawdź połączenie i spróbuj ponownie.',
    errServer: 'Serwer napotkał błąd. Spróbuj ponownie.',
    errUnavail:'Usługa RAG jest niedostępna. Upewnij się, że backend działa.',
    wTitle:    'MA3AK',
    wSub:      'Zadawaj pytania oparte na dostępnych dowodach klinicznych.',
    ex0: '• Jaki jest zalecany cel ciśnienia krwi?',
    ex1: '• Jakie są opcje leczenia pierwszego rzutu w nadciśnieniu?',
    ex2: '• Którzy pacjenci wymagają dodatkowego monitorowania sercowo-naczyniowego?',
    searchLang:'Wyszukaj język...',
    noLang:    'Nie znaleziono języków',
  },

  // ── Indonesian ────────────────────────────────────────────────────────────────
  id: {
    brandName: 'MA3AK',
    brandSub:  'RAG System',
    aiLabel:   'Asisten AI',
    newChat:   'Obrolan Baru',
    send:      'Kirim',
    answer:    'Jawaban',
    evidence:  'Bukti',
    sources:   'Sumber',
    confidence:'Keyakinan',
    page:      'Halaman',
    section:   'Bagian',
    placeholder:'Ajukan pertanyaan klinis...',
    inputHint: 'Enter untuk mengirim · Shift+Enter untuk baris baru',
    loading:   'Menghasilkan jawaban...',
    insufficient:    'Bukti Tidak Cukup',
    insufficientMsg: 'Dokumen klinis yang tersedia tidak mengandung informasi yang cukup untuk menjawab pertanyaan ini dengan aman.',
    confHigh:  'Tinggi',
    confMed:   'Sedang',
    confLow:   'Rendah',
    confInsuf: 'Tidak Cukup',
    errNetwork:'Kesalahan jaringan. Periksa koneksi Anda dan coba lagi.',
    errServer: 'Server mengalami kesalahan. Silakan coba lagi.',
    errUnavail:'Layanan RAG saat ini tidak tersedia. Pastikan backend sedang berjalan.',
    wTitle:    'MA3AK',
    wSub:      'Ajukan pertanyaan berdasarkan bukti klinis yang tersedia.',
    ex0: '• Apa target tekanan darah yang direkomendasikan?',
    ex1: '• Apa pilihan pengobatan lini pertama untuk hipertensi?',
    ex2: '• Pasien mana yang memerlukan pemantauan kardiovaskular tambahan?',
    searchLang:'Cari bahasa...',
    noLang:    'Tidak ada bahasa ditemukan',
  },

  // ── Thai ──────────────────────────────────────────────────────────────────────
  th: {
    brandName: 'MA3AK',
    brandSub:  'RAG System',
    aiLabel:   'ผู้ช่วย AI',
    newChat:   'สนทนาใหม่',
    send:      'ส่ง',
    answer:    'คำตอบ',
    evidence:  'หลักฐาน',
    sources:   'แหล่งอ้างอิง',
    confidence:'ความเชื่อมั่น',
    page:      'หน้า',
    section:   'ส่วน',
    placeholder:'ถามคำถามทางคลินิก...',
    inputHint: 'Enter เพื่อส่ง · Shift+Enter สำหรับบรรทัดใหม่',
    loading:   'กำลังสร้างคำตอบ...',
    insufficient:    'หลักฐานไม่เพียงพอ',
    insufficientMsg: 'เอกสารทางคลินิกที่มีอยู่ไม่มีข้อมูลเพียงพอที่จะตอบคำถามนี้อย่างปลอดภัย',
    confHigh:  'สูง',
    confMed:   'ปานกลาง',
    confLow:   'ต่ำ',
    confInsuf: 'ไม่เพียงพอ',
    errNetwork:'ข้อผิดพลาดเครือข่าย กรุณาตรวจสอบการเชื่อมต่อและลองใหม่',
    errServer: 'เซิร์ฟเวอร์พบข้อผิดพลาด กรุณาลองใหม่',
    errUnavail:'บริการ RAG ไม่พร้อมใช้งานในขณะนี้ กรุณาตรวจสอบว่าแบ็กเอนด์ทำงานอยู่',
    wTitle:    'MA3AK',
    wSub:      'ถามคำถามตามหลักฐานทางคลินิกที่มีอยู่',
    ex0: '• เป้าหมายความดันโลหิตที่แนะนำคือเท่าไร?',
    ex1: '• ทางเลือกการรักษาขั้นแรกสำหรับความดันโลหิตสูงคืออะไร?',
    ex2: '• ผู้ป่วยกลุ่มใดต้องการการติดตามหัวใจและหลอดเลือดเพิ่มเติม?',
    searchLang:'ค้นหาภาษา...',
    noLang:    'ไม่พบภาษา',
  },

  // ── Vietnamese ────────────────────────────────────────────────────────────────
  vi: {
    brandName: 'MA3AK',
    brandSub:  'RAG System',
    aiLabel:   'Trợ lý AI',
    newChat:   'Cuộc trò chuyện mới',
    send:      'Gửi',
    answer:    'Câu trả lời',
    evidence:  'Bằng chứng',
    sources:   'Nguồn',
    confidence:'Mức tin cậy',
    page:      'Trang',
    section:   'Mục',
    placeholder:'Đặt câu hỏi lâm sàng...',
    inputHint: 'Enter để gửi · Shift+Enter để xuống dòng',
    loading:   'Đang tạo câu trả lời...',
    insufficient:    'Bằng chứng không đủ',
    insufficientMsg: 'Các tài liệu lâm sàng hiện có không chứa đủ thông tin để trả lời câu hỏi này một cách an toàn.',
    confHigh:  'Cao',
    confMed:   'Trung bình',
    confLow:   'Thấp',
    confInsuf: 'Không đủ',
    errNetwork:'Lỗi mạng. Vui lòng kiểm tra kết nối và thử lại.',
    errServer: 'Máy chủ gặp lỗi. Vui lòng thử lại.',
    errUnavail:'Dịch vụ RAG hiện không khả dụng. Đảm bảo backend đang chạy.',
    wTitle:    'MA3AK',
    wSub:      'Đặt câu hỏi dựa trên bằng chứng lâm sàng hiện có.',
    ex0: '• Mục tiêu huyết áp được khuyến nghị là bao nhiêu?',
    ex1: '• Các lựa chọn điều trị đầu tay cho tăng huyết áp là gì?',
    ex2: '• Bệnh nhân nào cần theo dõi tim mạch bổ sung?',
    searchLang:'Tìm kiếm ngôn ngữ...',
    noLang:    'Không tìm thấy ngôn ngữ',
  },

  // ── Persian (Farsi) ───────────────────────────────────────────────────────────
  fa: {
    brandName: 'MA3AK',
    brandSub:  'RAG System',
    aiLabel:   'دستیار هوشمند',
    newChat:   'گفتگوی جدید',
    send:      'ارسال',
    answer:    'پاسخ',
    evidence:  'شواهد',
    sources:   'منابع',
    confidence:'اطمینان',
    page:      'صفحه',
    section:   'بخش',
    placeholder:'سوال بالینی بپرسید...',
    inputHint: 'Enter برای ارسال · Shift+Enter برای خط جدید',
    loading:   'در حال تولید پاسخ...',
    insufficient:    'شواهد ناکافی',
    insufficientMsg: 'اسناد بالینی موجود اطلاعات کافی برای پاسخ ایمن به این سوال ندارند.',
    confHigh:  'بالا',
    confMed:   'متوسط',
    confLow:   'پایین',
    confInsuf: 'ناکافی',
    errNetwork:'خطای شبکه. لطفاً اتصال خود را بررسی کرده و دوباره امتحان کنید.',
    errServer: 'سرور با خطا مواجه شد. لطفاً دوباره امتحان کنید.',
    errUnavail:'سرویس RAG در دسترس نیست. لطفاً مطمئن شوید که بکند در حال اجرا است.',
    wTitle:    'MA3AK',
    wSub:      'بر اساس شواهد بالینی موجود سوال بپرسید.',
    ex0: '• هدف توصیه‌شده برای فشار خون چیست؟',
    ex1: '• گزینه‌های درمان خط اول برای پرفشاری خون چیست؟',
    ex2: '• کدام بیماران نیاز به پایش قلبی‌عروقی اضافی دارند؟',
    searchLang:'جستجوی زبان...',
    noLang:    'زبانی یافت نشد',
  },

  // ── Urdu ──────────────────────────────────────────────────────────────────────
  ur: {
    brandName: 'MA3AK',
    brandSub:  'RAG System',
    aiLabel:   'AI معاون',
    newChat:   'نئی گفتگو',
    send:      'بھیجیں',
    answer:    'جواب',
    evidence:  'شواہد',
    sources:   'ذرائع',
    confidence:'اعتماد',
    page:      'صفحہ',
    section:   'قسم',
    placeholder:'طبی سوال پوچھیں...',
    inputHint: 'Enter بھیجنے کے لیے · Shift+Enter نئی لائن',
    loading:   'جواب تیار ہو رہا ہے...',
    insufficient:    'ناکافی شواہد',
    insufficientMsg: 'دستیاب طبی دستاویزات میں اس سوال کا محفوظ جواب دینے کے لیے کافی معلومات موجود نہیں ہیں۔',
    confHigh:  'اعلیٰ',
    confMed:   'درمیانہ',
    confLow:   'کم',
    confInsuf: 'ناکافی',
    errNetwork:'نیٹ ورک خرابی۔ براہ کرم اپنا کنکشن چیک کریں اور دوبارہ کوشش کریں۔',
    errServer: 'سرور میں خرابی آئی۔ براہ کرم دوبارہ کوشش کریں۔',
    errUnavail:'RAG سروس دستیاب نہیں ہے۔ یقینی بنائیں کہ بیک اینڈ چل رہا ہے۔',
    wTitle:    'MA3AK',
    wSub:      'دستیاب طبی شواہد کی بنیاد پر سوالات پوچھیں۔',
    ex0: '• تجویز کردہ بلڈ پریشر ہدف کیا ہے؟',
    ex1: '• ہائی بلڈ پریشر کے لیے پہلی لائن علاج کیا ہے؟',
    ex2: '• کن مریضوں کو اضافی قلبی نگرانی کی ضرورت ہے؟',
    searchLang:'زبان تلاش کریں...',
    noLang:    'کوئی زبان نہیں ملی',
  },

  // ── Bengali ───────────────────────────────────────────────────────────────────
  bn: {
    brandName: 'MA3AK',
    brandSub:  'RAG System',
    aiLabel:   'AI সহকারী',
    newChat:   'নতুন কথোপকথন',
    send:      'পাঠান',
    answer:    'উত্তর',
    evidence:  'প্রমাণ',
    sources:   'উৎস',
    confidence:'আস্থা',
    page:      'পৃষ্ঠা',
    section:   'বিভাগ',
    placeholder:'ক্লিনিকাল প্রশ্ন জিজ্ঞাসা করুন...',
    inputHint: 'পাঠাতে Enter · নতুন লাইনের জন্য Shift+Enter',
    loading:   'উত্তর তৈরি করা হচ্ছে...',
    insufficient:    'অপর্যাপ্ত প্রমাণ',
    insufficientMsg: 'উপলব্ধ ক্লিনিকাল নথিতে এই প্রশ্নের নিরাপদ উত্তর দেওয়ার জন্য পর্যাপ্ত তথ্য নেই।',
    confHigh:  'উচ্চ',
    confMed:   'মাঝারি',
    confLow:   'কম',
    confInsuf: 'অপর্যাপ্ত',
    errNetwork:'নেটওয়ার্ক ত্রুটি। সংযোগ পরীক্ষা করুন এবং পুনরায় চেষ্টা করুন।',
    errServer: 'সার্ভারে ত্রুটি হয়েছে। আবার চেষ্টা করুন।',
    errUnavail:'RAG পরিষেবা অনুপলব্ধ। ব্যাকএন্ড চলছে কিনা নিশ্চিত করুন।',
    wTitle:    'MA3AK',
    wSub:      'উপলব্ধ ক্লিনিকাল প্রমাণের উপর ভিত্তি করে প্রশ্ন করুন।',
    ex0: '• প্রস্তাবিত রক্তচাপ লক্ষ্য কী?',
    ex1: '• উচ্চ রক্তচাপের জন্য প্রথম সারির চিকিৎসার বিকল্পগুলি কী?',
    ex2: '• কোন রোগীদের অতিরিক্ত কার্ডিওভাসকুলার মনিটরিং প্রয়োজন?',
    searchLang:'ভাষা অনুসন্ধান করুন...',
    noLang:    'কোনো ভাষা পাওয়া যায়নি',
  },

  // ── Greek ─────────────────────────────────────────────────────────────────────
  el: {
    brandName: 'MA3AK',
    brandSub:  'RAG System',
    aiLabel:   'Βοηθός AI',
    newChat:   'Νέα συνομιλία',
    send:      'Αποστολή',
    answer:    'Απάντηση',
    evidence:  'Αποδεικτικά στοιχεία',
    sources:   'Πηγές',
    confidence:'Βεβαιότητα',
    page:      'Σελίδα',
    section:   'Ενότητα',
    placeholder:'Κάντε μια κλινική ερώτηση...',
    inputHint: 'Enter για αποστολή · Shift+Enter για νέα γραμμή',
    loading:   'Δημιουργία απάντησης...',
    insufficient:    'Ανεπαρκή στοιχεία',
    insufficientMsg: 'Τα διαθέσιμα κλινικά έγγραφα δεν περιέχουν αρκετές πληροφορίες για να απαντηθεί με ασφάλεια αυτή η ερώτηση.',
    confHigh:  'Υψηλή',
    confMed:   'Μέτρια',
    confLow:   'Χαμηλή',
    confInsuf: 'Ανεπαρκής',
    errNetwork:'Σφάλμα δικτύου. Ελέγξτε τη σύνδεσή σας και δοκιμάστε ξανά.',
    errServer: 'Ο διακομιστής αντιμετώπισε σφάλμα. Παρακαλώ δοκιμάστε ξανά.',
    errUnavail:'Η υπηρεσία RAG δεν είναι διαθέσιμη. Βεβαιωθείτε ότι το backend λειτουργεί.',
    wTitle:    'MA3AK',
    wSub:      'Κάντε ερωτήσεις βάσει διαθέσιμων κλινικών στοιχείων.',
    ex0: '• Ποιος είναι ο συνιστώμενος στόχος αρτηριακής πίεσης;',
    ex1: '• Ποιες είναι οι επιλογές θεραπείας πρώτης γραμμής για υπέρταση;',
    ex2: '• Ποιοι ασθενείς χρειάζονται επιπλέον καρδιαγγειακή παρακολούθηση;',
    searchLang:'Αναζήτηση γλώσσας...',
    noLang:    'Δεν βρέθηκαν γλώσσες',
  },

  // ── Czech ─────────────────────────────────────────────────────────────────────
  cs: {
    brandName: 'MA3AK',
    brandSub:  'RAG System',
    aiLabel:   'AI Asistent',
    newChat:   'Nový chat',
    send:      'Odeslat',
    answer:    'Odpověď',
    evidence:  'Důkazy',
    sources:   'Zdroje',
    confidence:'Jistota',
    page:      'Strana',
    section:   'Sekce',
    placeholder:'Položte klinický dotaz...',
    inputHint: 'Enter pro odeslání · Shift+Enter pro nový řádek',
    loading:   'Generování odpovědi...',
    insufficient:    'Nedostatečné důkazy',
    insufficientMsg: 'Dostupné klinické dokumenty neobsahují dostatek informací k bezpečnému zodpovězení této otázky.',
    confHigh:  'Vysoká',
    confMed:   'Střední',
    confLow:   'Nízká',
    confInsuf: 'Nedostatečná',
    errNetwork:'Chyba sítě. Zkontrolujte připojení a zkuste to znovu.',
    errServer: 'Server narazil na chybu. Zkuste to znovu.',
    errUnavail:'Služba RAG je aktuálně nedostupná. Ujistěte se, že backend běží.',
    wTitle:    'MA3AK',
    wSub:      'Pokládejte otázky na základě dostupných klinických důkazů.',
    ex0: '• Jaký je doporučený cíl krevního tlaku?',
    ex1: '• Jaké jsou možnosti léčby první linie hypertenze?',
    ex2: '• Kteří pacienti vyžadují dodatečné kardiovaskulární sledování?',
    searchLang:'Hledat jazyk...',
    noLang:    'Žádné jazyky nenalezeny',
  },

  // ── Swedish ───────────────────────────────────────────────────────────────────
  sv: {
    brandName: 'MA3AK',
    brandSub:  'RAG System',
    aiLabel:   'AI-Assistent',
    newChat:   'Ny chatt',
    send:      'Skicka',
    answer:    'Svar',
    evidence:  'Bevis',
    sources:   'Källor',
    confidence:'Konfidens',
    page:      'Sida',
    section:   'Avsnitt',
    placeholder:'Ställ en klinisk fråga...',
    inputHint: 'Enter för att skicka · Shift+Enter för ny rad',
    loading:   'Genererar svar...',
    insufficient:    'Otillräckliga bevis',
    insufficientMsg: 'De tillgängliga kliniska dokumenten innehåller inte tillräcklig information för att säkert besvara denna fråga.',
    confHigh:  'Hög',
    confMed:   'Medel',
    confLow:   'Låg',
    confInsuf: 'Otillräcklig',
    errNetwork:'Nätverksfel. Kontrollera din anslutning och försök igen.',
    errServer: 'Servern stötte på ett fel. Försök igen.',
    errUnavail:'RAG-tjänsten är inte tillgänglig. Se till att backend körs.',
    wTitle:    'MA3AK',
    wSub:      'Ställ frågor baserade på tillgängliga kliniska bevis.',
    ex0: '• Vilket blodtrycksmål rekommenderas?',
    ex1: '• Vilka är förstahandsbehandlingsalternativen för hypertoni?',
    ex2: '• Vilka patienter behöver ytterligare kardiovaskulär monitorering?',
    searchLang:'Sök språk...',
    noLang:    'Inga språk hittades',
  },

  // ── Danish ────────────────────────────────────────────────────────────────────
  da: {
    brandName: 'MA3AK',
    brandSub:  'RAG System',
    aiLabel:   'AI-Assistent',
    newChat:   'Ny chat',
    send:      'Send',
    answer:    'Svar',
    evidence:  'Evidens',
    sources:   'Kilder',
    confidence:'Konfidens',
    page:      'Side',
    section:   'Afsnit',
    placeholder:'Stil et klinisk spørgsmål...',
    inputHint: 'Enter for at sende · Shift+Enter for ny linje',
    loading:   'Genererer svar...',
    insufficient:    'Utilstrækkelig evidens',
    insufficientMsg: 'De tilgængelige kliniske dokumenter indeholder ikke nok information til at besvare dette spørgsmål sikkert.',
    confHigh:  'Høj',
    confMed:   'Middel',
    confLow:   'Lav',
    confInsuf: 'Utilstrækkelig',
    errNetwork:'Netværksfejl. Tjek din forbindelse og prøv igen.',
    errServer: 'Serveren stødte på en fejl. Prøv igen.',
    errUnavail:'RAG-tjenesten er ikke tilgængelig. Sørg for at backend kører.',
    wTitle:    'MA3AK',
    wSub:      'Stil spørgsmål baseret på tilgængelig klinisk evidens.',
    ex0: '• Hvad er det anbefalede blodtryksmål?',
    ex1: '• Hvad er førstevalgsmuligheder for hypertension?',
    ex2: '• Hvilke patienter kræver yderligere kardiovaskulær overvågning?',
    searchLang:'Søg sprog...',
    noLang:    'Ingen sprog fundet',
  },

  // ── Norwegian ─────────────────────────────────────────────────────────────────
  no: {
    brandName: 'MA3AK',
    brandSub:  'RAG System',
    aiLabel:   'AI-Assistent',
    newChat:   'Ny chat',
    send:      'Send',
    answer:    'Svar',
    evidence:  'Bevis',
    sources:   'Kilder',
    confidence:'Konfidens',
    page:      'Side',
    section:   'Seksjon',
    placeholder:'Still et klinisk spørsmål...',
    inputHint: 'Enter for å sende · Shift+Enter for ny linje',
    loading:   'Genererer svar...',
    insufficient:    'Utilstrekkelig bevis',
    insufficientMsg: 'De tilgjengelige kliniske dokumentene inneholder ikke nok informasjon til å besvare dette spørsmålet trygt.',
    confHigh:  'Høy',
    confMed:   'Middels',
    confLow:   'Lav',
    confInsuf: 'Utilstrekkelig',
    errNetwork:'Nettverksfeil. Sjekk tilkoblingen din og prøv igjen.',
    errServer: 'Serveren støtte på en feil. Vennligst prøv igjen.',
    errUnavail:'RAG-tjenesten er ikke tilgjengelig. Sørg for at backend kjører.',
    wTitle:    'MA3AK',
    wSub:      'Still spørsmål basert på tilgjengelig klinisk bevis.',
    ex0: '• Hva er det anbefalte blodtryksmålet?',
    ex1: '• Hva er førstelinjealternativer for hypertensjon?',
    ex2: '• Hvilke pasienter trenger ekstra kardiovaskulær overvåking?',
    searchLang:'Søk etter språk...',
    noLang:    'Ingen språk funnet',
  },

  // ── Finnish ───────────────────────────────────────────────────────────────────
  fi: {
    brandName: 'MA3AK',
    brandSub:  'RAG System',
    aiLabel:   'AI-Avustaja',
    newChat:   'Uusi keskustelu',
    send:      'Lähetä',
    answer:    'Vastaus',
    evidence:  'Näyttö',
    sources:   'Lähteet',
    confidence:'Luottamus',
    page:      'Sivu',
    section:   'Osio',
    placeholder:'Esitä kliininen kysymys...',
    inputHint: 'Enter lähettääksesi · Shift+Enter uudelle riville',
    loading:   'Luodaan vastausta...',
    insufficient:    'Riittämätön näyttö',
    insufficientMsg: 'Saatavilla olevat kliiniset asiakirjat eivät sisällä riittävästi tietoa vastatakseen tähän kysymykseen turvallisesti.',
    confHigh:  'Korkea',
    confMed:   'Keskikokoinen',
    confLow:   'Matala',
    confInsuf: 'Riittämätön',
    errNetwork:'Verkkovirhe. Tarkista yhteytesi ja yritä uudelleen.',
    errServer: 'Palvelin kohtasi virheen. Yritä uudelleen.',
    errUnavail:'RAG-palvelu ei ole käytettävissä. Varmista, että backend on käynnissä.',
    wTitle:    'MA3AK',
    wSub:      'Esitä kysymyksiä saatavilla olevan kliinisen näytön perusteella.',
    ex0: '• Mikä on suositeltu verenpainetavoite?',
    ex1: '• Mitkä ovat ensisijaiset hoitovaihtoehdot verenpainetaudille?',
    ex2: '• Ketkä potilaat tarvitsevat lisää sydän- ja verisuoniseurantaa?',
    searchLang:'Hae kieltä...',
    noLang:    'Kieliä ei löydy',
  },

};

// ── Public helpers ────────────────────────────────────────────────────────────

/**
 * Translate a key for the given language code.
 * Falls back to English if the key is not found.
 * @param {string} key
 * @param {string} [code]  — defaults to 'en'
 * @returns {string}
 */
function t(key, code) {
  const lang = code || 'en';
  const bundle = TRANSLATIONS[lang] || TRANSLATIONS.en;
  return bundle[key] !== undefined ? bundle[key] : (TRANSLATIONS.en[key] || key);
}

/**
 * Get language metadata by code.
 * Returns English as fallback.
 * @param {string} code
 * @returns {{ code:string, nativeName:string, englishName:string, dir:string }}
 */
function getLang(code) {
  return LANGUAGES.find(l => l.code === code) || LANGUAGES[0];
}
